### ISSUE TITLE
[DOC] Social Media Icons - Low Contrast

### ISSUE THREAD

**Issue by Akshu-on-github** [dsc-srmrmp/dsc-srmrmp.github.io#11]
## Description

<img src = "https://user-images.githubusercontent.com/61582763/136658364-7150a737-498d-4ffa-946d-8f4d70f7ca0a.png" width = 50% align = "right">

I noticed a few things:
- The contrast isn't sufficient
- The alignment isn't proper

### What I'd like to do
- [ ] Add new icons
- [ ] Align the icons properly

If possible, I'd like to work on this issue

**Comment by IMMANUEL44** [comment]
Hey! 

Cool to have you here. Excited to see you work here and appreciate your interest to work and contribute for us . Please do go ahead and fix the issues we would be glad and love to see you work for us
