### ISSUE TITLE
Add scroll to the top feature

### ISSUE THREAD

**Issue by IMMANUEL44** [dsc-srmrmp/dsc-srmrmp.github.io#2]
**What is scroll to the top?**

**Scroll To Top** tries to minimize this effort by providing an intuitive icon at the bottom-right corner of each page so that with one click you will be at the top of the page with beautiful animation. No more searching for the Home key on your keyboard and no more dragging of the scroll bar

**Comment by IMMANUEL44** [comment]
@Khushboo288 

Sure thing!

We will accept the contribution for sure :smile: . Do make the necessary pull request and then our team will review it and then we will merge it as soon as possible with the hactober tag if it is approved we will link it here and assign it to you and also assign you to the issues once the pull request is made.

Happy Contributing :smiley:

**Comment by harshvardhan614** [comment]
@Khushboo288 mam, please assign this issue to me, I will definitely give you results.
please assign me under hactoberfest tag. Thank you

**Comment by IMMANUEL44** [comment]
@harikishantk @Khushboo288 assigning to both of ya but only the first one to make a pull request with proper codes will be merged after reviewing

**Comment by IMMANUEL44** [comment]
Hey!

Can you assing this issue to me please? i woud like to work on this issues heart_eyes

**Comment by Khushboo288** [comment]
Added a code please check it and review it and merge my Pr #17 . I am hacktoberfest contributer.
